### ISSUE TITLE
Changes on source code are not reflected on diff panel

### ISSUE THREAD

**Issue by ceztko** [jzoss/Git-Source-Control-Provider#79] opened 2017-07-06 14:09 UTC
Step to reproduce:
- Start with no pending changes;
- Edit one file;
- Click on pending changes file list the edited file. Observe the changes;
- Edit the file again: the diff window is not updated;
- Press the Refresh button: the button does nothing.

**Comment by OvidiuCaba** [comment] 2017-07-29 14:02
I believe that this is related to issue 74: https://github.com/jzoss/Git-Source-Control-Provider/issues/74

If that gets solved, this gets solved, as well. We're waiting for the fix to be pushed in prod.

**Comment by jzoss** [comment] 2017-08-15 15:26
I think you guys have something setup slightly differently. I did not get the same error.. It refreshed for me.. So.. can you give me the path for the project you are using? It's probably a case I am just not seeing.

**Comment by OvidiuCaba** [comment] 2017-08-15 15:54
I use VS 2015 and VS 2017 with TortoiseGit.

I provided a possible solution in the other thread (#74). The problem is that the method GetCaseSensitiveFileName() doesn't return the path with the correct case. Because of that incorrect casing, we have these undesired effects. If we fix the method to return the correct casing, everything will be OK [I can confirm that after testing the possible solution on my local machine].

**Comment by jzoss** [comment] 2017-08-15 15:59
I was pretty sure I fixed that in the last CI build in the release tab.. Check out https://github.com/jzoss/Git-Source-Control-Provider/compare/master...jzoss:dev

Anyway.. I will look more into it.

**Comment by OvidiuCaba** [comment] 2017-08-15 20:48
The link that you provided is a comparison between master and dev.

If you look at the commits in master branch:

https://github.com/jzoss/Git-Source-Control-Provider/commits/master

You can see that you updated the version on Jun 26, 2017.

But if you have a look on the dev branch:

https://github.com/jzoss/Git-Source-Control-Provider/commits/dev

You can see that the fix is merged into dev branch on Jun 5, 2017. However, this fix was never merged from dev into master. A version update is not contained by dev branch. This makes me think that on Jun 26, you updated the version on master and released a package which does not contain the fix.

**Comment by jzoss** [comment] 2017-08-15 20:51
No the CI build comes from the Dev branch.

**Comment by OvidiuCaba** [comment] 2017-08-15 20:54
I understand. Maybe just redo the package and I will test it again. It is strange that it worked on my local machine when I changed the code, but the new version of the extensions doesn't work. After I test it [the future new version], I give you a second feedback and we'll see what we need to do next... But hopefully, it will work :)

**Comment by jzoss** [comment] 2017-08-15 21:00
Yea..I'll check again.. if not.. I'll try and debug it a bit..

**Comment by jzoss** [comment] 2017-08-15 21:13
Ok try 1.7.1.17.. I just made ti build again.. with 1 extra bug fix.

**Comment by OvidiuCaba** [comment] 2017-08-15 21:25
Diff works. Show Log works. Blame works. :)

**Comment by jzoss** [comment] 2017-08-15 21:37
Nice.

**Comment by ceztko** [comment] 2017-08-16 10:13
I just installed 1.17.1.17 and I am still having issues with the problem reported in this ticket. The steps to reproduce are the same, I will extend the description:

- Start with no pending changes;
- Edit one file;
- Click on pending changes file list the edited file. Observe the changes;
- Edit the file again: the diff window is **not** updated (at the current feature level, is supposed to be updated automatically on file change?);
- Press the Refresh button: the button does nothing, the file is still showing **previous** changes: this is of course wrong behavior, the new changes should be detected and shown accordingly.

**Comment by OvidiuCaba** [comment] 2017-08-16 19:26
I've just tested and, when I perform the second modification on the file, a message popups: "Do you want to load the changed files?". I choose Yes and the comparison window is refreshed, reflecting the last changes.

**Comment by ceztko** [comment] 2017-08-16 23:17
> I perform the second modification on the file, a message
> popups: "Do you want to load the changed files?"

I think there are still a misunderstanding: I am always editing the file within Visual Studio, not externally. What I am observing is diff panel refresh on the current visualized file is not performed after a second Visual Studio editor modification (and all following ones).

**Comment by OvidiuCaba** [comment] 2017-08-17 17:43
> I am always editing the file within Visual Studio, not externally

Me, too :) While keeping the Diff window open, I went in Visual Studio and changes the opened file in the Diff window. And the behavior is the one that I explained in the above message.

**Comment by ceztko** [comment] 2017-08-17 18:54
> I went in Visual Studio and changes the opened file in the Diff window

No, please repeat the steps using just the visual studio editor when required to make a change to a file and tell me if you can reproduce. It's a very basic use case.

**Comment by ceztko** [comment] 2017-08-18 11:09
The flow is so basic that maybe you don't have the bug and something is set up differently like @jzoss suggests. Please, look at this video:

https://drive.google.com/file/d/0B5eakb6RdPhANWZuU1BQRVdER3c/view?usp=sharing

My system is:
Windows 10 Pro 1703 64bit
Git SCC 1.7.1.17
TortoiseGit 2.5.0.0
git version 2.14.1.windows.1

**Comment by ceztko** [comment] 2017-08-18 13:50
> I am sorry, but it looks like I did not understand the steps

Then, did you reproduce?

**Comment by OvidiuCaba** [comment] 2017-08-18 15:43
I was able to reproduce, but that diff window is pretty stupid. In order to trigger a refresh, you need to select another file, then come back to the file you want to have its diff refreshed [you can do that if you have at least two files in pending changes]. Another issue is if you have a long file, you won't be able to see the changes made at the bottom of the file. In order to do that, you need to increase the diff window height. Why don't you use this option?

![alternativetodiff](https://user-images.githubusercontent.com/6516996/29466281-049a703e-8445-11e7-8c48-9c5f86027696.PNG)

I personally never use the diff window that you use. Instead I always review my code before committing using the compare window that I suggested in the attached image.

**Comment by ceztko** [comment] 2017-08-18 16:02
> I was able to reproduce the issue, but that diff window is pretty stupid

Good. The window is not stupid, it just have the bug I reported in this ticket. I find it very useful to quickly review files.


> Another issue is if you have a long file, you won't be able
> to see the changes made at the bottom of the file

That is a regression caused by a recent issue I asked to resolve in #77. Basically I asked the diff panel to be set read-only, since there's no useful side effect of letting it editable. @jzoss made id disabled by mistake, making it not scrollable. Setting it just readonly should fix it.

**Comment by jzoss** [comment] 2017-08-18 16:23
Oh I get it.. Ok.. I can try try and fix that one. @ceztko thanks for the video.

**Comment by jzoss** [comment] 2017-08-23 15:58
Try the latest CI build. It should be fixed

**Comment by ceztko** [comment] 2017-08-23 17:30
Fixed for me, thanks

**Closed** 2017-08-31 17:58 UTC
Labels: bug
