### ISSUE TITLE
Null Exception on History (1.5.0.50)

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#40] opened 2016-03-03 09:37 UTC
If I try to open the GitUI History thingy, It crashes with an NullException

![image](https://cloud.githubusercontent.com/assets/5390116/13490239/c4df1912-e12b-11e5-93e5-64db636f173e.png)

**Comment by jzoss** [comment] 2016-03-04 18:50
@teebee76 Still have this issue? I have yet to recreate.. Does it happen on all you repos?

**Comment by jzoss** [comment] 2016-03-04 20:23
Ok check out build 51.. I think I may have figured out the cause.

**Comment by jzoss** [comment] 2016-03-31 18:45
Fixed in upcoming 1.5.1

**Closed** 2016-03-31 18:45 UTC
